Update I

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -54,9 +54,16 @@ jobs:
 
     - name: Run tests in Docker
       continue-on-error: true
+      env:
+        BASE_URL: ${{ vars.BASE_URL }}
+        AUTH_USER_NAME: ${{ secrets.AUTH_USER_NAME }}
+        AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
       run: |
         mkdir -p reports
         docker run --rm \
+          -e BASE_URL="$BASE_URL" \
+          -e AUTH_USER_NAME="$AUTH_USER_NAME" \
+          -e AUTH_PASSWORD="$AUTH_PASSWORD" \
           -v ${{ github.workspace }}/reports:/tests/reports \
           -v ${{ github.workspace }}/videos:/tests/videos \
           ui-tests ./run.sh
@@ -76,6 +83,18 @@ jobs:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: allure-report
     
+    - name: Send Teams Notification
+      if: always()   # send even if tests fail
+      run: |
+        MESSAGE="UI Automation Tests Run Completed. \nAllure Report:
+            https://alexkaminskiy.github.io/ui-automation-tests/"
+
+            curl -H "Content-Type: application/json" \
+                -d "{\"text\": \"${MESSAGE}\"}" \
+                ${{ secrets.TEAMS_WEBHOOK_URL }}
+    
+    - name: Cleanup
+      run: docker rm -f locust-master worker-1 worker-2 worker-3 || true
     - name: Mark job as failed if tests failed
       if: failure()
       run: exit 1
